
platform :ios, '9.0'

target 'StackRecette' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleSignIn'

  # Pods for StackRecette

  target 'StackRecetteTests' do
    inherit! :search_paths
    pod 'GoogleSignIn'
  end

  target 'StackRecetteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
